= Date to day number conversion and vice-versa

There are several day numbering conventions commonly used in computing and science:

* Julian Day Number
* Unix day number - the number of days since 1 January 1970
* Excel day number (also called the OLE Automation day number or _OADate_). The number of days since
30th December 1899.

We will use the last of these conventions to show how to change between a date and a day number. A
day number is occasionally called a serial date.

== Showing the Excel day number

* In Excel we can simply enter a date and change the format to number in order to see the day number.
* In Powershell: +
----
(Get-Date).ToOADate()
----
* In C#: +
----
Console.WriteLine(DateTime.Today.ToOADate());
----

== The problem (and solution!)

Dates are normally specified as a year, month and day - so how to we convert this to a serial number?

Let's start by choosing an false starting point for the year of the 1st March. This is so that the leap day
which is inserted at the end of February in a leap year is the last day of our "false" year. We also
number months starting at zero - not one. 

We note that in order to calculate the day number of the first of the month, we could use a lookup table
as follows:

[source,c#]
----
int[] monthDays = { 0, 31, 61, 92, 122, 153, 184, 214, 245, 275, 306, 337 };
----

So the first day of February in our *false* year is day 337 (the first day of March is, of course, day zero).

It turns out that, long ago, someone turned this series into a set of points ( (0, 0), (1, 31), (2, 61) etc. ) and
found that the day number *n* is related to the false month number *m* by the following equation:

[source,c#]
----
n = 30.6013986m + 0.0256410
----

This produces the sequence of real numbers as follows:

|===
| 0 |0.0256410256410504 | 0  
| 1 |30.6270396270397   | 30
| 2 |61.2284382284383   | 61
| 3 |91.8298368298369   | 92
| 4 |122.431235431235   | 122
| 5 |153.032634032634   | 153
| 6 |183.634032634033   | 184
| 7 |214.235431235431   | 214
| 8 |244.83682983683    | 245
| 9 |275.438228438228   | 275
| 10 |306.039627039627  | 306
| 11 | 336.641025641026 | 337
|===


== Alternative formula

This formula is due to Van Flandern.

Consider a calendar with no leap years - the number of days from year zero until the 1st January on year x is given
by 

[source,c#]
----
365 * x
----

If, for the time being, we consider the case where leap years occur every four years (ignoring the 100 and 400
year rules), we can find after some experimentation that the number of days from 1st January year zero until
the 1st January year y is given by:

[source,c#]
----
367 * y - (7 * y / 4) 
----

*using integer division*.

[The `7 * y / 4` component increases in a series as follows: 1, 3, 5, 7, 8, 10, 12, 14, 15, 17, 19, 21, 22...
In other words, it increases by two every normal year (365 days) since we need to subtract 2 days from 367. It
increases by 1 every leap year (366 days) since we need to subtract 1 day from 367.

== Adding business days to a date

We may need to add, for example, four business days to a date. Say this date happens to be Friday, we 
would expect the result to be Thursday as Thursday is the fourth business day after Friday.

If we add *five* business days to a date, then the resulting *day* is the same since five business
days is a full week. The same applies to any multiple of five business days. So, for example 20
business days after Wednesday 1st February 2017 is Wednesday 1st March 2017.

If we have a number that is *not* divisible by 5, then we can add the part that is divisible by 5 first
then add the remainder. So if we wish to add 28 business days, we will first add five full weeks (`28 / 5`) then
add the 3 remaining business days (`28 % 5`). However, if in adding the remainder, we go past a weekend, then
we need to add two extra days since Saturday and Sunday do not count as business days.

It turns out that OADates (Excel dates) are "_Saturday-based_". This means that the epoch of 30 Dec 1899 is
a Saturday - thus if we have a C# `DateTime` and do the following:

[source,c#]
----
var date = DateTime.Today;
var day = (int)date.ToOADate() % 7;
----

`day` will contain zero for Saturday.

So we can tell if a DateTime represents a weekend day by the following test:

[source,c#]
----
if ((int)date.ToOADate() % 7 < 2)
{
    Console.WriteLine("It's the weekend!");
}
---- 

So, to add N business days to an OADate (which is represented by a positive integer),
we will first add the correct number of full weeks: 

[source,c#]
----
static int AddBusinessDays(int startDate, int n)
{
    var newDate = startDate + n / 5 * 7;

    return newDate;
}
----

Next, we need to add the remainder, but we need to add two more days if going past or landing on a weekend
(or subtract two more days if N is negative and we go backwards past or land on a weekend).

We can form a the following table - the starting day is in the first column and the number of days
to add are in the top row.

[cols="^s,^,^,^,^,^,^,^,^,^"]
|===
| 9+^| *Days to add*
s|Start day s| -4 s| -3 s| -2 s| -1 s| 0 s| 1 s| 2 s| 3 s| 4 
| 2 (Monday) | -2 | -1 | 0 | 1 | 2 | 3 | 4 | 5 | 6
| 3 (Tuesday) | -1 | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7
| 4 (Wednesday) | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8  
| 5 (Thursday) | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 
| 6 (Friday) | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10  
|===

The results are shown in the main body of the table - we can see which results are below 2 - this indicates
we need to *subtract* two more days to compensate for a weekend when N is negative. We can also see which 
values are greater than 7 indicating that we need to *add* two more days to compensate for a weekend when
N is positive.

We can do this by taking the startday

[source,c#]
----
static int AddBusinessDays(int startDate, int n)
{
    var newDate = startDate + n / 5 * 7;

    int originalDay = startDate % 7; // 0-6 with 0 meaning Saturday
    int remainder = n % 5;
    int newDay = originalDay + remainder;
    int correction = (newDay < 2) ? -2 : (newday > 6 ? 2 : 0); // weekend correction
    return newDate;
}
----

We can also note that for d in the range -4 to +10, the function `f(x) => 2 * ((x + 3) / 5 - 1)` using integer
divisision generates the sequence `-2, -2, -2, -2, -2, -2, 0, 0, 0, 0, 0, 2, 2, 2, 2` so we can replace
our nested ternary operator as follows:

[source,c#]
----
static int AddBusinessDays(int startDate, int n)
{
    // split number of days into full business weeks and a remainder. Adding or subtracting a
    // multiple of five business days will always land us on the same day, so
    // for every five business days we add a whole week (7 days):
    var remainder = n % 5;
    int originalDay = startDate % 7;

    int newDay = originalDay + remainder;

    // factor to correct for weekends when adding remainder:
    var correction = 2 * ((newDay + 3) / 5 - 1);

    var newDate = startDate + n / 5 * 7 + remainder + correction;

    return newDate;
}
----

Note that, we do not consider the case where the *starting date* is on Saturday or Sunday since it is not 
clear what we should do in this case. The business rules of the application should determine this behaviour:
it may be enough (or even actually be desirable) in some cases to throw an exception if the starting date
is Saturday or Sunday:

[source,c#]
----
if (startDate % 7 < 2)
{
    throw new ArgumentException($"the supplied start date {startDate} is Saturday or Sunday");
}
----

== Business days between two dates

[source,c#]
----
static int GetNumberOfBusinessDaysInRange(int oaDate1, int oaDate2)
{
    var day1 = oaDate1 % 7;
    if (day1 < 2)
    {
        oaDate1 += 2 - day1;
    }

    var day2 = oaDate2 % 7;
    if (day2 < 2)
    {
        oaDate2 -= day2;
    }

    var days = (oaDate2 - oaDate1) / 7 * 5;
    var remainder = (oaDate2 - oaDate1) % 7;
    var correction = (day1 + remainder) / 7 + (day1 + remainder) / 8;

    days += remainder - correction;
    return days;
}
----
